---
- name: Deploy Flask app
  hosts: g1
  remote_user: centos

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes
      become: yes

    - name: Install necessary packages
      yum:
        name:
          - python3-pip
          - git
        state: present
      become: yes
    - name: Create virtual environment
      command: python3 -m venv /opt/myapp/env
      become: yes
    - name: Activate virtual environment
      command: /bin/bash -c "source /opt/myapp/env/bin/activate"
      become: yes
    - name: Install flask using pip
      pip:
        name: flask
        executable: /opt/myapp/env/bin/pip
      become: yes
    - name: Start Flask app
      become: true
      command: /bin/bash -c "source /opt/myapp/env/bin/activate && export FLASK_APP=/opt/myapp/app.py && /opt/myapp/env/bin/flask run --host=0.0.0.0 &"
      async: 0
      poll:  0

